# Regularization In Machine Leaning

In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import sklearn
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,mean_absolute_error

In [41]:
boston = pd.read_csv('load_boston.csv')
boston

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  target  
0       15.3  396.90   4.98    24.0  
1       17.8  396.90   9.14    21.6  
2       17.8  392.83   4.03    34.7  
3       18.7  394.63   2.94    33.4  
4       18.7  396.90   5.33    36.2  
..       ...     ...    ...     ...  
501     21.0  391.99   9.67    22.4  
502     21.0  396.90   9.08    20.6  
503     21.0  396.90   5.64    23.9  
504     21.0  393.45   6.48    22.0  
505     21.0  396.90   7.88    11.9  

[506 rows x 14 columns]

In [42]:
boston.keys()

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'target'],
      dtype='object')

In [43]:
boston.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'target'],
      dtype='object')

In [44]:
boston.target

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: target, Length: 506, dtype: float64

In [45]:
x = boston.iloc[:,0:-1]

In [46]:
x

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [47]:
y = boston.iloc[:,-1]

In [48]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: target, Length: 506, dtype: float64

In [49]:
x.shape

(506, 13)

In [50]:
y.shape

(506,)

In [51]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.33,random_state=42)

In [52]:
x_train.shape

(339, 13)

In [53]:
y_train.shape

(339,)

In [54]:
x_test.shape

(167, 13)

In [55]:
y_test.shape

(167,)

In [56]:
lm = LinearRegression()

In [57]:
lm.fit(x_train,y_train)

LinearRegression()

In [58]:
lm.coef_

array([-1.28749718e-01,  3.78232228e-02,  5.82109233e-02,  3.23866812e+00,
       -1.61698120e+01,  3.90205116e+00, -1.28507825e-02, -1.42222430e+00,
        2.34853915e-01, -8.21331947e-03, -9.28722459e-01,  1.17695921e-02,
       -5.47566338e-01])

In [59]:
lm.intercept_

33.334975755635924

In [60]:
lm.score(x_train,y_train)

0.7392344370995025

In [61]:
 # predict the value , using predict method
pred=lm.predict(x_test) #predicted result of House price
print('predict the price:',pred)
print('Actual Price:',y_test) #Actual Result of Actual answers of House price

predict the price: [28.53469469 36.6187006  15.63751079 25.5014496  18.7096734  23.16471591
 17.31011035 14.07736367 23.01064388 20.54223482 24.91632351 18.41098052
 -6.52079687 21.83372604 19.14903064 26.0587322  20.30232625  5.74943567
 40.33137811 17.45791446 27.47486665 30.2170757  10.80555625 23.87721728
 17.99492211 16.02608791 23.268288   14.36825207 22.38116971 19.3092068
 22.17284576 25.05925441 25.13780726 18.46730198 16.60405712 17.46564046
 30.71367733 20.05106788 23.9897768  24.94322408 13.97945355 31.64706967
 42.48057206 17.70042814 26.92507869 17.15897719 13.68918087 26.14924245
 20.2782306  29.99003492 21.21260347 34.03649185 15.41837553 25.95781061
 39.13897274 22.96118424 18.80310558 33.07865362 24.74384155 12.83640958
 22.41963398 30.64804979 31.59567111 16.34088197 20.9504304  16.70145875
 20.23215646 26.1437865  31.12160889 11.89762768 20.45432404 27.48356359
 10.89034224 16.77707214 24.02593714  5.44691807 21.35152331 41.27267175
 18.13447647  9.8012101  21.24024

In [62]:
print('error')
# Called it from --> (from sklearn.metrics import mean_squared_error,mean_absolute_error)
print('mean_absolute_error:',mean_absolute_error(y_test,pred))
print('Mean_squared_error:',mean_squared_error(y_test,pred))
print('Root_Mean_squared_error:',np.sqrt(mean_squared_error(y_test,pred)))

error
mean_absolute_error: 3.1482557548168266
Mean_squared_error: 20.724023437339767
Root_Mean_squared_error: 4.552364598463063


# Regularization L1 an L2

L1 - Lasso Regression
L2 - Ridge Regression

In [64]:
from sklearn.linear_model import Lasso,Ridge

In [65]:

#alpha values could be--> 0.0001, 0.001, 0.01, 0.1, 1, 10 ---> higher values reduce all coefficients to Zero

ls=Lasso(alpha=.0001)
#ls=lasso(alpha=1.0) -> By Default
ls.fit(x_train,y_train)
print(ls.score(x_train,y_train))
predlasso=ls.predict(x_test)
print(mean_squared_error(y_test,predlasso))
print('mean_squared_error :',np.sqrt(mean_squared_error(y_test,predlasso)))

0.7392343937634267
20.72474300493454
mean_squared_error : 4.552443630066663


In [66]:
ls.coef_

array([-1.28721337e-01,  3.78268297e-02,  5.80577642e-02,  3.23688640e+00,
       -1.61345703e+01,  3.90196728e+00, -1.28766062e-02, -1.42166457e+00,
        2.34775264e-01, -8.21646961e-03, -9.28326015e-01,  1.17707288e-02,
       -5.47663411e-01])

In [69]:
#try to minimize coeficient varience

rd=Ridge(alpha=0.0001)
rd.fit(x_train,y_train)
print(rd.score(x_train,y_train))

predridge=rd.predict(x_test)
print(mean_squared_error(y_test,predridge))
print('mean squared error : ',np.sqrt(mean_squared_error(y_test,predridge)))

0.7392344370110338
20.72406786133194
mean squared error :  4.552369477682138


In [70]:
rd.coef_

array([-1.28748444e-01,  3.78234053e-02,  5.82039140e-02,  3.23863768e+00,
       -1.61681850e+01,  3.90205604e+00, -1.28521788e-02, -1.42220008e+00,
        2.34850085e-01, -8.21346290e-03, -9.28704068e-01,  1.17696373e-02,
       -5.47569890e-01])

In [71]:
#Elasticnet both combination of Lasso and Ridge

from sklearn.linear_model import ElasticNet
enr = ElasticNet(alpha=0.0001)
enr.fit(x_train,y_train)
enrpred=enr.predict(x_test)
print(enr.score(x_train,y_train))

pred=enr.predict(x_test)

print('mean squared error: ',np.sqrt(mean_squared_error(y_test,pred)))
enr.coef_

0.7392316519886222
mean squared error:  4.553246312760975


array([-1.28523550e-01,  3.78554691e-02,  5.69673672e-02,  3.23267088e+00,
       -1.58813070e+01,  3.90281088e+00, -1.30960614e-02, -1.41791313e+00,
        2.34177614e-01, -8.23880066e-03, -9.25462939e-01,  1.17776904e-02,
       -5.48207230e-01])

# Regressor -
Regression purposse

In [72]:
from sklearn.svm import SVR

In [73]:
svr = SVR(kernel='linear')
svr.fit(x_train,y_train)
print(svr.score(x_train,y_train))
pred_y=svr.predict(x_test)
print('Mean squared error: ',np.sqrt(mean_squared_error(y_test,pred_y)))

svr = SVR(kernel='poly')
svr.fit(x_train,y_train)
print(svr.score(x_train,y_train))
pred_y=svr.predict(x_test)
print('Mean squared error: ',np.sqrt(mean_squared_error(y_test,pred_y)))

svr = SVR(kernel='rbf')
svr.fit(x_train,y_train)
print(svr.score(x_train,y_train))
pred_y=svr.predict(x_test)
print('Mean squared error: ',np.sqrt(mean_squared_error(y_test,pred_y)))

0.6970552501315544
Mean squared error:  4.994665544028643
0.1888227759257124
Mean squared error:  7.505715530350019
0.1746863516580558
Mean squared error:  7.413902381152258


In [74]:
from sklearn.svm import SVR

In [75]:
# Using for loop iterate all
kernelList=['linear','poly','rbf']
for i in kernelList:
    sv=SVR(kernel=i)
    sv.fit(x_train,y_train)
    print("Score of ",i,"=",sv.score(x_train,y_train))
    sv.predict(x_test)
    print('Mean squared error: ',i,np.sqrt(mean_squared_error(y_test,pred_y)))


Score of  linear = 0.6970552501315544
Mean squared error:  linear 7.413902381152258
Score of  poly = 0.1888227759257124
Mean squared error:  poly 7.413902381152258
Score of  rbf = 0.1746863516580558
Mean squared error:  rbf 7.413902381152258
